# ddasSort Configuration file using TOML parser
# <- For comments

[Experiment]
Lab = "NSCL"
name = "e12024"
dataDir = "remote/root-files/" # Assumes NSCL ddasDumper + UnbuildData.C format
#Also, don't forget the / at the end of directories!

#For detector arrays, by calling [[Arrays]] this will add to the list of Arrays
[[Arrays]]
name = "DSSDfrontHiGain"
calibrationFile = "Calibrations/alphaFront.dat" 
#can store channels in this file, look at provided file for example
#REMEMBER - all channels are defined by unique channel mapping function defined in RBDDASChannel.cpp

[[Arrays]]
name = "DSSDfrontLoGain"
channelListFile = "IDK"
#need to provide channel list at very least

[[Arrays]]
name = "DSSDbackHiGain"
calibrationFile = "Calibrations/alphaBack.dat"

[[Arrays]]
name = "DSSDbackLoGain"
channelListFile = "IDK"

[[Arrays]]
name = "SeGA"
calibrationFile = "IDK"

#For singular detectors, similarly this will add to a list of Detectors
[[Detectors]]
name = "PIN1"
channel = 1

[[Detectors]]
name = "PIN2"
channel = 2

[[Detectors]]
name = "TOF"
channel = 5

