# ddasSort Configuration file using TOML parser
# <- For comments

[Experiment]
Lab = "NSCL"
name = "e12024"
dataDir = "/home/EventData/e12024/root-files/" #"remote/root-files/" # Assumes NSCL ddasDumper + UnbuildData.C format
#Also, don't forget the / at the end of directories!

[Analysis]
coinWindow = 5000 # 5us
corrWindow = 5E9 # 5s
stripTolerance = 3

#For detector arrays, by calling [[Arrays]] this will add to the list of Arrays
[[Arrays]]
name = "DSSDhiGainFront"
calibrationFile = "Calibrations/alphaCalibFrontDSSD.dat" 
#can store channels in this file, look at provided file for example
#REMEMBER - all channels are defined by unique channel mapping function defined in RBDDASChannel.cpp

[[Arrays]]
name = "DSSDloGainFront"
channelListFile = "Calibrations/DSSDloFrontChannels.dat"
#need to provide channel list at very least

[[Arrays]]
name = "DSSDhiGainBack"
calibrationFile = "Calibrations/alphaCalibBackDSSD.dat"

[[Arrays]]
name = "DSSDloGainBack"
channelListFile = "Calibrations/DSSDloBackChannels.dat"

[[Arrays]]
name = "SeGA"
calibrationFile = "Calibrations/SeGACalib.dat"

[[Arrays]]
name = "SSD"
calibrationFile = "Calibrations/alphaCalibrationSSD.dat"

#For singular detectors, similarly this will add to a list of Detectors
[[Detectors]]
name = "PIN1"
channel = 0

[[Detectors]]
name = "PIN2"
channel = 1

[[Detectors]]
name = "TOF"
channel = 5

[[Detectors]]
name = "XFP"
channel = 6
